version: 2
project_name: isite
builds:
  - env:
      - CGO_ENABLED=0
    id: isite
    main: cmd/isite/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kemingy/isite/pkg/version.gitTag={{ .Tag }}
      - -X github.com/kemingy/isite/pkg/version.buildDate={{ .Date }}
      - -X github.com/kemingy/isite/pkg/version.gitCommit={{ .Commit }}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

changelog:
  use: github
  sort: asc
  groups:
    - title: 'Exciting New Features 🎉'
      regexp: "^.*feat.*"
      order: 0
    - title: 'Bug Fix 🛠'
      regexp: "^.*(Fix|fix|bug).*"
      order: 1
    - title: 'Refactor 🏗️'
      regexp: "^.*refact.*"
      order: 2
    - title: 'Documentation 🖊️'
      regexp: "^.*docs.*"
      order: 3
    - title: 'Others:'
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/kemingy/isite:{{ .Version }}-amd64"
    use: buildx
    dockerfile: .github/releaser.Dockerfile
    ids:
      - isite
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/kemingy/isite:{{ .Version }}-arm64"
    use: buildx
    dockerfile: .github/releaser.Dockerfile
    ids:
      - isite
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/kemingy/isite:{{ .Version }}"
    image_templates:
      - "ghcr.io/kemingy/isite:{{ .Version }}-amd64"
      - "ghcr.io/kemingy/isite:{{ .Version }}-arm64"
